/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PresentationsRouteImport } from './routes/presentations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EditorIndexRouteImport } from './routes/editor/index'
import { Route as InteractIndexRouteImport } from './routes/interact/index'
import { Route as EditorPresentationIdIndexRouteImport } from './routes/editor/$presentationId/index'
import { Route as InteractSessionCodeIndexRouteImport } from './routes/interact/$sessionCode/index'
import { Route as PresentPresentationIdIndexRouteImport } from './routes/present/$presentationId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsRoute = PresentationsRouteImport.update({
  id: '/presentations',
  path: '/presentations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractIndexRoute = InteractIndexRouteImport.update({
  id: '/interact/',
  path: '/interact/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorPresentationIdIndexRoute =
  EditorPresentationIdIndexRouteImport.update({
    id: '/editor/$presentationId/',
    path: '/editor/$presentationId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InteractSessionCodeIndexRoute =
  InteractSessionCodeIndexRouteImport.update({
    id: '/interact/$sessionCode/',
    path: '/interact/$sessionCode/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PresentPresentationIdIndexRoute =
  PresentPresentationIdIndexRouteImport.update({
    id: '/present/$presentationId/',
    path: '/present/$presentationId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/presentations': typeof PresentationsRoute
  '/settings': typeof SettingsRoute
  '/editor/': typeof EditorIndexRoute
  '/interact/': typeof InteractIndexRoute
  '/editor/$presentationId/': typeof EditorPresentationIdIndexRoute
  '/interact/$sessionCode/': typeof InteractSessionCodeIndexRoute
  '/present/$presentationId/': typeof PresentPresentationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/presentations': typeof PresentationsRoute
  '/settings': typeof SettingsRoute
  '/editor': typeof EditorIndexRoute
  '/interact': typeof InteractIndexRoute
  '/editor/$presentationId': typeof EditorPresentationIdIndexRoute
  '/interact/$sessionCode': typeof InteractSessionCodeIndexRoute
  '/present/$presentationId': typeof PresentPresentationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/presentations': typeof PresentationsRoute
  '/settings': typeof SettingsRoute
  '/editor/': typeof EditorIndexRoute
  '/interact/': typeof InteractIndexRoute
  '/editor/$presentationId/': typeof EditorPresentationIdIndexRoute
  '/interact/$sessionCode/': typeof InteractSessionCodeIndexRoute
  '/present/$presentationId/': typeof PresentPresentationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/presentations'
    | '/settings'
    | '/editor/'
    | '/interact/'
    | '/editor/$presentationId/'
    | '/interact/$sessionCode/'
    | '/present/$presentationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/presentations'
    | '/settings'
    | '/editor'
    | '/interact'
    | '/editor/$presentationId'
    | '/interact/$sessionCode'
    | '/present/$presentationId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/presentations'
    | '/settings'
    | '/editor/'
    | '/interact/'
    | '/editor/$presentationId/'
    | '/interact/$sessionCode/'
    | '/present/$presentationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PresentationsRoute: typeof PresentationsRoute
  SettingsRoute: typeof SettingsRoute
  EditorIndexRoute: typeof EditorIndexRoute
  InteractIndexRoute: typeof InteractIndexRoute
  EditorPresentationIdIndexRoute: typeof EditorPresentationIdIndexRoute
  InteractSessionCodeIndexRoute: typeof InteractSessionCodeIndexRoute
  PresentPresentationIdIndexRoute: typeof PresentPresentationIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations': {
      id: '/presentations'
      path: '/presentations'
      fullPath: '/presentations'
      preLoaderRoute: typeof PresentationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interact/': {
      id: '/interact/'
      path: '/interact'
      fullPath: '/interact/'
      preLoaderRoute: typeof InteractIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$presentationId/': {
      id: '/editor/$presentationId/'
      path: '/editor/$presentationId'
      fullPath: '/editor/$presentationId/'
      preLoaderRoute: typeof EditorPresentationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interact/$sessionCode/': {
      id: '/interact/$sessionCode/'
      path: '/interact/$sessionCode'
      fullPath: '/interact/$sessionCode/'
      preLoaderRoute: typeof InteractSessionCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$presentationId/': {
      id: '/present/$presentationId/'
      path: '/present/$presentationId'
      fullPath: '/present/$presentationId/'
      preLoaderRoute: typeof PresentPresentationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PresentationsRoute: PresentationsRoute,
  SettingsRoute: SettingsRoute,
  EditorIndexRoute: EditorIndexRoute,
  InteractIndexRoute: InteractIndexRoute,
  EditorPresentationIdIndexRoute: EditorPresentationIdIndexRoute,
  InteractSessionCodeIndexRoute: InteractSessionCodeIndexRoute,
  PresentPresentationIdIndexRoute: PresentPresentationIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
